kumuluzee:
  name: users-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UserDataDS
      connection-url: jdbc:postgresql://localhost:5432/microserviceDB
      username: postgres
      password: docker
      max-pool-size: 20

  config:
    consul:
        agent: 'http://localhost:8500'

rest-properties:
  maintenance-mode: false