name: Maven build and upload to DockerHub

on:
  schedule:
    - cron: 0 0 * * *
  push:
  pull_request:
    branches: 
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.1.0
      
      - name: Fetch current time
        id: current-time
        uses: josStorer/get-current-time@v2.0.2
        with:
          format: YYYY-MM-DD-HH-mm-ss
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile_with_maven_build
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image-catalog:${{ steps.current-time.outputs.formattedTime }}
